<a href="https://colab.research.google.com/github/sunyeon-Jeong/python_MachineLearning/blob/main/python_MachineLearning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **python_MachineLearning-1**

In [ ]:
print("Python Machine Learning")

Python Machine Learning


## **Pandas**

### 1️⃣ Pandas 테이블구조

In [ ]:
# pandas 라이브러리 임포트
import pandas as pandas

### 2️⃣ DataFrame

In [ ]:
# name, age, sex -> Column
dataframe = pandas.DataFrame(
    {
        "Name" : [
            "Brand, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age" : [22, 35, 58],
        "Sex" : ["male", "male", "female"],
    }
)

In [ ]:
# dataframe 확인
dataframe

Name  Age     Sex
0    Brand, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [ ]:
# dataframe -> 1개의 Column 확인
dataframe["Age"]

0    22
1    35
2    58
Name: Age, dtype: int64

### 3️⃣ Series

In [ ]:
# Series : 2차원 데이터
ages = pandas.Series([20, 30, 40], name = "Age")

In [ ]:
# Series 확인
ages

0    20
1    30
2    40
Name: Age, dtype: int64

In [ ]:
# 최대값 확인
dataframe["Age"].max()
ages.max()

40

## **Numpy**

In [ ]:
# numpy 라이브러리 임포트
import numpy as numpy

### 1️⃣ array 생성

In [ ]:
# 1차원
a = numpy.array([1, 2, 3, 4, 5, 6])

In [ ]:
# 1차원 확인
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 2차원
b = numpy.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
# 2차원 확인
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# array index 활용
b[0, 0]
b[0:2, 0] # x이상 : y미만 범위표현

array([1, 3])

In [ ]:
# 0으로 채워진 array
numpy.zeros([2, 3]) # (행, 열)

array([[0., 0., 0.],
       [0., 0., 0.]])

### 2️⃣ array 차원, 크기, 모양

In [ ]:
array_example = numpy.array([[[0, 1, 2, 3],
                              [4, 5, 6, 7]],

                             [[0, 1, 2, 3],
                              [4, 5, 6, 7]],

                             [[0, 1, 2, 3],
                              [4, 5, 6, 7]]])

In [ ]:
# 차원
array_example.ndim

3

In [ ]:
# 크기
array_example.size

24

In [ ]:
# 모양
array_example.shape

(3, 2, 4)

### 3️⃣ array 모양 바꾸기

In [ ]:
# 1차원 array
data = numpy.array([1, 2, 3, 4, 5, 6])
data

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 2차원으로 변환
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 2차원으로 변환
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# 2차원 transform (선형대수)
transformData = data.reshape(3, 2)

transformData.T

array([[1, 3, 5],
       [2, 4, 6]])

## **기본연산**

In [ ]:
# 더하기
data = numpy.array([[1, 2], [3, 4], [5, 6]])

# 3행2열 + 1행2열 -> 모든 행에 더함
one_row = numpy.array([1, 1])
data + one_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
# 전체 array에서 최대값
data.max()

6

In [ ]:
# 전체 array에서 최소값
data.min()

1

In [ ]:
# 전체 array 합계
data.sum()

21

## **파일데이터 읽기/쓰기**

In [ ]:
# google drive 연결
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 저장할데이터 생성
csv_array = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [ ]:
# csv 파일로 저장
numpy.savetxt('/content/drive/MyDrive/python_MachineLearning/new_file.csv', csv_array)

In [ ]:
# csv 파일 불러오기
numpy.loadtxt('/content/drive/MyDrive/python_MachineLearning/new_file.csv')

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])